matcher_config: 'correspondence/configs/lepard_plants.yaml'
matcher_weights: 'correspondence/pretrained/plants_S1-single_weights.pth'

outlier_rejection_config: 'correspondence/configs/outlier_rejection.yaml'
outlier_rejection_weights: 'correspondence/pretrained/outlier_plants_S1-single_weights.pth'


mode: test
gpu_mode:  True

exp_dir: None


#dataset:
dataset: plants
folder: deploy
batch_size: 1
num_workers: 1
augment_noise: 0.002
data_root: data_plants
split: {
  "train": plants_S1-single/partitioned-final/train,
  "val": plants_S1-single/partitioned-final/val,
  "test": plants_S1-single/partitioned-final/test
}
