matcher_config: 'correspondence/configs/lepard.yaml'
matcher_weights: 'correspondence/pretrained/plants_S5_weights.pth'

outlier_rejection_config: 'correspondence/configs/outlier_rejection.yaml'
outlier_rejection_weights: 'correspondence/pretrained/outlier_S5_weights.pth'


mode: test
gpu_mode:  True

exp_dir: None


#dataset:
dataset: plants
folder: deploy
batch_size: 1
num_workers: 1
augment_noise: 0.002
data_root: data_plants/S5/subsets
split: {
  "train": train,
  "val": val,
  "test": test
}
