gpu_mode: True
deformation_model: NDP


use_ldmk: True
ldmk_config: "./correspondence/configs/correspondence_plants_S1.yaml"

num_workers: 4
batch_size: 1
augment_noise: False


use_depth: False

w_ldmk: 1
w_cd: &w_cd 0.001
w_reg: &w_reg 0.0005

trunc_cd: &trunc_cd 0.4


# motion representation
motion_type : &motion_type  "SE3" # option  [ "Sim3", "SE3", "sflow"]
rotation_format : &rotation_format  "axis_angle" # options [ "6D", "quaternion", "axis_angle", "euler"]

#optimization
iters: &iters 500
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
max_break_count: 15
break_threshold_ratio: 0.001


# threshold of inlier match
inlier_thr : &inlier_thr 0.4
reject_outliers: &reject_outliers True

samples: &samples 2000

#pyramid configuration
m : &m 10
k0 : &k0 -8
depth: &depth 3
width: &width 128
act_fn: relu




#dataset
data_root : "data_plants/S1-single/subsets"
split: { 'test': "test" }

#experiment
exp_dir :  !join [ reject, *reject_outliers, ithr, *inlier_thr, 'wcd', *w_cd, 'trunccd', *trunc_cd, 'wreg', *w_reg ]
folder: LNDP_S1_on_S1
